name: 'Flyway Rollback Module'
 
on: 
  workflow_dispatch:
    inputs:
      SchemaName:
       description: 'Schema Name'     
       required: true
      MigrationFolder:
       description: 'Migration Folder Path'     
       required: true
      UndoVersion:
        description: 'Undo Version'     
        required: true
 
env:
    DOCKER_IMAGE: redgate/flyway
    SCHEMAS: '${{ github.event.inputs.SchemaName }}'
    MigrationPath: '${{ github.event.inputs.MigrationFolder }}'
    UndoVersion: '${{ github.event.inputs.UndoVersion }}'
 
jobs:
 Failed-Action:
      name: Rollback Job
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v3.0.0
      
      - name: Notify Failure
        run: echo "The 'build' job has failed. Taking appropriate action..."
        
      - run: >-
         docker run --rm
         --volume ${{ github.workspace }}/"${{ env.MigrationPath }}":/flyway/sql:ro
         --volume ${{ github.workspace }}/reports:/flyway/reports
         "${{ env.DOCKER_IMAGE }}"
         -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
         -url="${{ secrets.DB_TEST_URL }}"/"${{ env.SCHEMAS }}"
         -user="${{ secrets.DB_TEST_USERNAME }}"
         -password="${{ secrets.DB_TEST_PASSWORD }}"  
         -reportFilename="reports/report"   
         repair -schemas="${{ env.SCHEMAS }}"
          
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/"${{ env.MigrationPath }}":/flyway/sql:ro
          --volume ${{ github.workspace }}/reports:/flyway/reports
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.DB_TEST_URL }}"/"${{ env.SCHEMAS }}"
          -user="${{ secrets.DB_TEST_USERNAME }}"
          -password="${{ secrets.DB_TEST_PASSWORD }}"  
          -reportFilename="reports/report"
          undo -target="${{ env.UndoVersion }}" -schemas="${{ env.SCHEMAS }}"

      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/"${{ env.MigrationPath }}":/flyway/sql:ro
          --volume ${{ github.workspace }}/reports:/flyway/reports
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.DB_TEST_URL }}"/"${{ env.SCHEMAS }}"
          -user="${{ secrets.DB_TEST_USERNAME }}"
          -password="${{ secrets.DB_TEST_PASSWORD }}"  
          -reportFilename="reports/report"  
          info -schemas="${{ env.SCHEMAS }}"


      - uses: actions/upload-artifact@v3
        if: always()
        with:
           name: flyway-rollback-report
           path: ${{ github.workspace }}/reports/report.html
