name: 'Dry Run Module'
 
on:
 workflow_dispatch:
   inputs:
       SchemaName:
        description: 'Schema Name'     
        required: true
       MigrationFolder:
        description: 'Migration Folder Path'     
        required: true
env:
    SQLFLUFF_DIALECT: mysql
    DOCKER_IMAGE: redgate/flyway
    SCHEMAS: '${{ github.event.inputs.SchemaName }}'
    MigrationPath: '${{ github.event.inputs.MigrationFolder }}'
    
jobs:
  Dry-run-Job:
    name: Dry Run / Syntax Checking
    runs-on: ubuntu-20.04
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Dry Run Job Execution
        run: >-
          docker run --rm
          --volume ${{ github.workspace }}/"${{ env.MigrationPath }}":/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.DB_TEST_URL }}"/"${{ env.SCHEMAS }}"
          -user="${{ secrets.DB_TEST_USERNAME }}"
          -password="${{ secrets.DB_TEST_PASSWORD }}" 
          migrate -dryRunOutput="--volume ${{ github.workspace }}/dryrun.sql" -validateOnMigrate=true
                  
      - name: Real Schema Info Check
        run: >-    
          docker run --rm
          --volume ${{ github.workspace }}/migrations:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.DB_TEST_URL }}"/"${{ env.SCHEMAS }}"
          -user="${{ secrets.DB_TEST_USERNAME }}"
          -password="${{ secrets.DB_TEST_PASSWORD }}" 
          info -dryRunSql


 
