name: Liquibase_Action

on:
  workflow_dispatch:
   push:
     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run 'Flyway status' in a Docker Container	    
      uses: docker://redgate/flyway:latest
      with:
        args: --url=jdbc:singlestore://svc-4f5248c3-aa85-45d7-a05f-eebd9cc0ccf9-dml.aws-virginia-6.svc.singlestore.com:3306/s2_dataset_martech_fb308a56 --changeLogFile=./Docker/changeLog.h2.sql --username=admin --password=password status --verbose
    

