name: 'Flyway Info Module'
 
on:
 workflow_dispatch: 
      
env:
    DOCKER_IMAGE: redgate/flyway
    SCHEMAS: devdb
 
jobs:
          
  Deploy-Test:
      name: Info Check
      runs-on: ubuntu-20.04
    #  if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
      - uses: actions/checkout@v3.0.0
      
      - run: >-    
          docker run
          --volume ${{ github.workspace }}/migrations:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.DB_TEST_URL }}"
          -user="${{ secrets.DB_TEST_USERNAME }}"
          -password="${{ secrets.DB_TEST_PASSWORD }}"  
          info -schemas="${{ env.SCHEMAS }}"
     
      - run: >-
          ls && cp -r migrations/* prod-migrations/ && pwd && tree
          
      - run: >-
          cd /home && ls
      
