name: 'Path Test'
 
on:
# workflow_dispatch: 
#on:
 # workflow_run:
  #  workflows:
   #   - Dry Run Module
    #types:
     # - completed
      
  workflow_dispatch:       
   inputs:
       SchemaName:
        description: 'Schema Name'     
        required: false
       MigrationFolder:
        description: 'Migration Folder Path'     
        required: false
    
env:
    DOCKER_IMAGE: redgate/flyway
    SCHEMAS: '${{ github.event.inputs.SchemaName }}'
    MigrationPath: '${{ github.event.inputs.MigrationFolder }}'
 
jobs:

 extract-value:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Read and Set Environment Variable
          id: extract
          run: |
            ls

            # Extract the value from the text file (replace with your extraction command)
            extracted_value=$(grep "SCHEMA:" dar-mig/migration-config.txt | cut -d " " -f 2-)
            echo "Extracted Value: $extracted_value"
            
            # Set the extracted value as an environment variable for later steps
            echo "ExtractedValue=$extracted_value" >> $GITHUB_ENV
            
        - name: Use Extracted Value
          run: |
            # Access the environment variable in subsequent steps
            echo "Value extracted from text file: $ExtractedValue"  
