name: 'Sanity Test Module'
 
on:
  workflow_run:
    workflows:
      - Flyway Dev Deploy Module
    types:
      - completed
      
env:
    DOCKER_IMAGE: redgate/flyway
    SCHEMAS: devdb
 
jobs:
          
  Deploy-Test:
      name: Deploy to Dev
      runs-on: ubuntu-20.04
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
      - uses: actions/checkout@v3.0.0
      
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/sanity-test:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.DB_TEST_URL }}"
          -user="${{ secrets.DB_TEST_USERNAME }}"
          -password="${{ secrets.DB_TEST_PASSWORD }}"   
          validate -schemas="${{ env.SCHEMAS }}"
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/sanity-test:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
          -url="${{ secrets.DB_TEST_URL }}"
          -user="${{ secrets.DB_TEST_USERNAME }}"
          -password="${{ secrets.DB_TEST_PASSWORD }}"   
          info -schemas="${{ env.SCHEMAS }}"
          
          
