name: SQL Fluff Check

on:
 workflow_dispatch:

jobs:
  sqlfluff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install sqlfluff
        run: pip install sqlfluff

      - name: Run sqlfluff check
        run: sqlfluff lint "${{ github.workspace }}/migration-2" --dialect=mysql --exclude-rules=L001,L002,L009,L010,L014,L029
